---

- name: Set installed Helm version
  command: "helm version --client --template '{{ '{{' }} .Client.SemVer {{ '}}' }}'"
  register: _helm_local_version
  changed_when: False
  ignore_errors: True
  check_mode: False

- name: Fail if Helm version does NOT match exactly (major, minor and patch)
  fail:
    msg:
      Local Helm version does NOT match the requirements ({{ _helm_local_version.stdout }}).
      Please install Helm v{{ helm_version }}
  when: ('v' + helm_version) != _helm_local_version.stdout
