---

- name: Set installed Helm version
  command: "helm version"
  register: _helm_local_version
  changed_when: False
  ignore_errors: True
  check_mode: False

- name: Fail if Helm version does NOT match exactly (major, minor and patch)
  fail:
    msg:
      Local Helm version ({{ _helm_local_version.stdout }}) does NOT match the requirements.
      Please install Helm v{{ helm_version }}
  when: ('v' + helm_version) != _helm_local_version.stdout
