---

###
### Ensure Helm is installed
###
- name: Check if Helm binary exists
  shell: command -v helm >/dev/null 2>&1
  register: _helm_exist
  changed_when: False
  ignore_errors: True
  check_mode: False

- name: Fail if Helm command does NOT exist
  fail:
    msg: "Helm command doesn NOT exist. Please install Helm v{{ helm_version }}"
  when: _helm_exist.rc != 0


###
### Ensure local Helm version is correct
###
- include_tasks: check-version-strict.yml
  when:
    - helm_version_strict|bool == True

- include_tasks: check-version-loose.yml
  when:
    - helm_version_strict|bool == False


###
### Run
###
- include_tasks: run.yml
