---

###
### Main entrypoint
###

- include: install-helm.yml
  tags:
    # Leave this tag at the bottom
    # Tests rely on its position
    - helm-install

- name: Update tiller
  command: "{{ helm_local_path }} init --upgrade"

- name: Get the latest list of charts
  command: "{{ helm_local_path }} repo update"

- name: Get all Helm releases
  command: "{{ helm_local_path }} list --all --output yaml"
  register: get_releases_command

- name: Parse all Helm releases
  set_fact:
    # Resource: https://stackoverflow.com/a/39852380
    helm_raw_releases: "{{ get_releases_command.stdout | from_yaml }}"

- name: Get array of release names
  set_fact:
    helm_release_names: "{{ helm_raw_releases.Releases | map(attribute='Name') | list }}"

- name: Install chart (if release does NOT exist yet)
  command: |
    {{ helm_local_path }} install {{ item.release }}
      --version {{ item.chart_version }}
      --namespace {{ item.namespace }}
      --values {{ helm_configuration_files }}/{{ item.values_file_path }}
      --name {{ item.release }}
  with_items: "{{ helm_charts }}"
  when: item.release not in helm_release_names

- name: Update chart (if release exist already)
  command: |
    {{ helm_local_path }} upgrade
      --version {{ item.chart_version }}
      --namespace {{ item.namespace }}
      --values {{ helm_configuration_files }}/{{ item.values_file_path }}
      {{ item.release }} {{ item.chart }}
  with_items: "{{ helm_charts }}"
  when: item.release in helm_release_names
