---

- name: Initialize local config
  command: |
    helm init
      {% if helm_kubectl_context is defined and helm_kubectl_context %}
      --kube-context {{ helm_kubectl_context }}
      {% endif %}
      --client-only
  check_mode: False
  changed_when: False

- name: Get Helm repositories
  command: |
    helm repo list
      {% if helm_kubectl_context is defined and helm_kubectl_context %}
      --kube-context {{ helm_kubectl_context }}
      {% endif %}
  register: _get_repositories_command
  check_mode: False
  changed_when: False

- name: Parse all Helm repositories
  parse_helm_repositories:
    helm_output: "{{ _get_repositories_command.stdout }}"
  register: _get_repositories
  check_mode: False

- name: Add new repositories
  command: |
    helm repo add
      {% if helm_kubectl_context is defined and helm_kubectl_context %}
      --kube-context {{ helm_kubectl_context }}
      {% endif %}
      {{ item.name }} {{ item.url }}
  with_items: "{{ helm_repositories }}"
  check_mode: False
  when: item.name not in _get_repositories.repository_names

- name: Get the latest list of charts
  command: |
    helm repo update
      {% if helm_kubectl_context is defined and helm_kubectl_context %}
      --kube-context {{ helm_kubectl_context }}
      {% endif %}
  check_mode: False
  changed_when: False

- name: Get all Helm releases
  command: |
    helm list
      {% if helm_kubectl_context is defined and helm_kubectl_context %}
      --kube-context {{ helm_kubectl_context }}
      {% endif %}
      --all
      --output yaml
  register: _get_releases_command
  check_mode: False
  changed_when: False

- name: Parse all Helm releases
  set_fact:
    # Resource: https://stackoverflow.com/a/39852380
    helm_raw_releases: "{{ _get_releases_command.stdout | from_yaml }}"

- name: Get array of release names
  set_fact:
    helm_release_names: >-
      {%- if 'Releases' in helm_raw_releases -%}
      {{ helm_raw_releases.Releases | map(attribute='Name') | list }}
      {%- else -%}
      {{ [] }}
      {%- endif %}

- name: Create temporary files to store the rendered template
  tempfile:
    state: file
  register: rendered_template
  with_items: "{{ helm_charts }}"
  check_mode: False
  changed_when: False

- template:
    src: "{{ helm_configuration_files }}/{{ item.item.values_file_path }}"
    dest: "{{ item.path }}"
    mode: '0400'
  with_items: "{{ rendered_template.results }}"
  check_mode: False
  changed_when: False

###
### Split between normal run and dry run
###
- include_tasks: run-normal.yml
  # Run without --check mode
  when: ansible_check_mode == False

- include_tasks: run-dry.yml
  # Run only in --check mode
  when: ansible_check_mode == True
