---

- name: Update tiller
  command: |
    helm init
      {% if helm_kubectl_context is defined and helm_kubectl_context %}
      --kube-context {{ helm_kubectl_context }}
      {% endif %}
      --client-only
  check_mode: False
  changed_when: False

- name: Get the latest list of charts
  command: |
    helm repo update
      {% if helm_kubectl_context is defined and helm_kubectl_context %}
      --kube-context {{ helm_kubectl_context }}
      {% endif %}
  check_mode: False
  changed_when: False

- name: Get all Helm releases
  command: |
    helm list
      {% if helm_kubectl_context is defined and helm_kubectl_context %}
      --kube-context {{ helm_kubectl_context }}
      {% endif %}
      --all
      --output yaml
  register: _get_releases_command
  check_mode: False
  changed_when: False

- name: Parse all Helm releases
  set_fact:
    # Resource: https://stackoverflow.com/a/39852380
    helm_raw_releases: "{{ _get_releases_command.stdout | from_yaml }}"

- name: Get array of release names
  set_fact:
    helm_release_names: >-
      {%- if 'Releases' in helm_raw_releases -%}
      {{ helm_raw_releases.Releases | map(attribute='Name') | list }}
      {%- else -%}
      {{ [] }}
      {%- endif %}

###
### Split between normal run and dry run
###
- include_tasks: run-normal.yml
  # Run without --check mode
  when: ansible_check_mode == False

- include_tasks: run-dry.yml
  # Run only in --check mode
  when: ansible_check_mode == True
